### ISSUE TITLE
Error, can't find ffmpeg

### ISSUE THREAD

**Issue by laag115** [kylophone/loudness#4]
In Ubuntu 16.10, installing ffmpeg does not have a folder in usr/local/bin, so loudness.rb can't use it's tools. How would I go about installing ffmpeg so it has the necessary tools in /usr/local/bin/ffmpeg

Error message:
`/usr/lib/ruby/2.3.0/open3.rb:199:in `spawn': No such file or directory - /usr/local/bin/ffmpeg (Errno::ENOENT)
	from /usr/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
	from /usr/lib/ruby/2.3.0/open3.rb:95:in `popen3'
	from ./loudness.rb:27:in `<main>'
`

**Comment by kylophone** [comment]
Edit this line: https://github.com/kylophone/loudness/blob/master/loudness.rb#L6

As long as `ffmpeg` is installed in your path, running `which ffmpeg` in a shell will give you what you're looking for.
